version: '2'
services:
  php-apache:
    container_name: symfony-docker
    build: .
    working_dir: /app
    expose:
      - 80
    ports:
      - 8080:80
    volumes:
      - ../symfony_app:/app
    environment:
      - SYMFONY_ENV=dev
      - SYMFONY_DEBUG=1